modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/yourname/modapi/issues"

[[mods]]
modId="modapi_example"
version="1.0.0"
displayName="ModAPI Example"
updateJSONURL="https://example.com/updates.json"
displayURL="https://github.com/yourname/modapi"
logoFile="modapi_example.png"
credits="Thanks to the Minecraft and NeoForge community"
authors="Your Name"
description='''
Example implementation using the ModAPI framework.
Demonstrates how to use the core, energy, and machinery modules.
'''

[[dependencies.modapi_example]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.5.0-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modapi_example]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modapi_example]]
    modId="modapi_core"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.modapi_example]]
    modId="modapi_energy"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.modapi_example]]
    modId="modapi_machinery"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
