# This is a configuration file for NeoForge
modLoader="javafml"
loaderVersion="[7.0,8.0)" # Updated for compatibility with JavaFML 7.0.10 in NeoForge 1.21.5
license="All Rights Reserved"
issueTrackerURL="https://github.com/AstroFrame/GalacticExpansion/issues"

[[mods]]
modId="galacticmachinery"
version="0.1.0"
displayName="Galactic Machinery"
displayURL="https://github.com/AstroFrame/GalacticExpansion"
credits="The AstroFrame Team"
authors="AstroFrame"
description='''
Machinery module for the Galactic Expansion mod.
Adds various industrial machines and automation systems.
'''

# NeoForge dependency for 1.21.5
[[dependencies.galacticmachinery]]
    modId="neoforge"
    type="required"
    versionRange="[21.5,)"  # Requires NeoForge 21.5 or later
    ordering="NONE"
    side="BOTH"

# Minecraft dependency for 1.21.5
[[dependencies.galacticmachinery]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5,1.22)"  # Requires Minecraft 1.21.5 but less than 1.22
    ordering="NONE"
    side="BOTH"
    
# Core module dependency
[[dependencies.galacticmachinery]]
    modId="galacticcore"
    type="required"
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
# Power module dependency
[[dependencies.galacticmachinery]]
    modId="galacticpower"
    type="required"
    versionRange="[0.1.0,)"
    ordering="AFTER"
    side="BOTH"