modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/astroframe/galactic-expansion/issues"

[[mods]]
modId="galacticcore"
version="1.0.0"
displayName="Galactic Core"
# updateJSONURL="https://example.com/updates.json"
# displayURL="https://example.com/"
logoFile="galacticcore-icon.png"
authors="AstroFrame Team"
description='''A modular Minecraft mod API for Neoforge 1.21.5'''

[[dependencies.galacticcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5, 1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.galacticcore]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.5.0-beta,)"
    ordering="NONE"
    side="BOTH"