# This is a configuration file for NeoForge
modLoader="javafml"
loaderVersion="[47,)" # Minimum version of the mod loader required to load the mod. For NeoForge 1.21.x - use 47+
license="All Rights Reserved"
issueTrackerURL="https://github.com/AstroFrame/GalacticExpansion/issues"

[[mods]]
modId="galacticcore"
version="0.1.0"
displayName="Galactic Core"
displayURL="https://github.com/AstroFrame/GalacticExpansion"
credits="The AstroFrame Team"
authors="AstroFrame"
description='''
Core module for the Galactic Expansion mod.
Contains shared APIs and utilities for all modules.
'''

# NeoForge dependency for 1.21.5
[[dependencies.galacticcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.5,)"  # Requires NeoForge 21.5 or later
    ordering="NONE"
    side="BOTH"

# Minecraft dependency for 1.21.5
[[dependencies.galacticcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5,1.22)"  # Requires Minecraft 1.21.5 but less than 1.22
    ordering="NONE"
    side="BOTH"