modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="galacticenergy"
version="${file.jarVersion}"
displayName="Galactic Energy Systems"
authors="AstroFrame Team"
description='''
Energy generation, storage, and transmission systems for the Galactic Expansion mod.
Provides a comprehensive energy API for other modules.
'''

[[dependencies.galacticenergy]]
modId="neoforge"
mandatory=true
versionRange="[21.4,)"
ordering="NONE"
side="BOTH"

[[dependencies.galacticenergy]]
modId="minecraft"
mandatory=true
versionRange="[1.21.4,1.22)"
ordering="NONE"
side="BOTH"