package com.astroframe.galactic.energy.api;

import net.minecraft.resources.ResourceLocation;

/**
 * Enumeration of energy types in the Galactic Expansion mod.
 * Different types of energy have different properties and compatibility.
 */
public enum EnergyType {
    /**
     * Standard electrical energy, compatible with most machines.
     */
    ELECTRICAL("electrical"),
    
    /**
     * Thermal energy, generated by heat sources.
     */
    THERMAL("thermal"),
    
    /**
     * Kinetic energy, generated by movement.
     */
    KINETIC("kinetic"),
    
    /**
     * Quantum energy, rare and powerful.
     */
    QUANTUM("quantum");
    
    private final String id;
    
    EnergyType(String id) {
        this.id = id;
    }
    
    /**
     * Gets the unique ID for this energy type.
     * 
     * @return The energy type ID
     */
    public String getId() {
        return id;
    }
    
    /**
     * Gets the ResourceLocation for this energy type.
     * 
     * @return The ResourceLocation
     */
    public ResourceLocation getResourceLocation() {
        return ResourceLocation.fromNamespaceAndPath("galacticexpansion", "energy/" + id);
    }
    
    /**
     * Gets an energy type by ID.
     * 
     * @param id The energy type ID
     * @return The energy type, or ELECTRICAL if not found
     */
    public static EnergyType byId(String id) {
        for (EnergyType type : values()) {
            if (type.getId().equals(id)) {
                return type;
            }
        }
        return ELECTRICAL; // Default
    }
}