name: Build Project

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: |
          export JAVA_HOME="$(dirname $(dirname $(readlink -f $(which java))))"
          ./gradlew clean build
      
      - name: Upload Core Module Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: core-module
          path: core/build/libs/*.jar
          if-no-files-found: error
      
      - name: Upload Energy Module Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: energy-module
          path: energy/build/libs/*.jar
          if-no-files-found: error
      
      - name: Upload Machinery Module Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: machinery-module
          path: machinery/build/libs/*.jar
          if-no-files-found: error
      
      - name: Upload Example Module Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: example-module
          path: example/build/libs/*.jar
          if-no-files-found: error