name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
      
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changelog
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
      
      - name: Upload Core Mod
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./core/build/libs/galacticexpansion-core-${{ github.ref_name }}.jar
          asset_name: galacticexpansion-core-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
      
      - name: Upload Energy Module
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./energy/build/libs/galacticexpansion-energy-${{ github.ref_name }}.jar
          asset_name: galacticexpansion-energy-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
      
      - name: Upload Machinery Module
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./machinery/build/libs/galacticexpansion-machinery-${{ github.ref_name }}.jar
          asset_name: galacticexpansion-machinery-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
      
      - name: Upload Example Module
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./example/build/libs/galacticexpansion-example-${{ github.ref_name }}.jar
          asset_name: galacticexpansion-example-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive